### ISSUE TITLE
Request - generate a toy example

### ISSUE THREAD

**Issue by tomersagi** [ldbc-dev/ldbc_snb_datagen_deprecated2015#17]
Hi,
I may be wrong, but it seems that the minimal example generated is 1GB large. 
It's too big if I want to debug a workload. I manually created a toy example by deleting a lot of rows, but it was a painstaking process and will probably not work as soon as something changes. It would be great if you could have a small 10 person graph generated using some special SF or flag. 
Thanks
Tomer

**Comment by alexaverbuch** [comment]
take a look at this one, too: https://github.com/ldbc-dev/ldbc_snb_interactive_validation
it's larger than you request, but much smaller than 1GB

**Comment by tomersagi** [comment]
This is great. You really should post this stuff to a mailing list I can subscribe to. Would've saved me a lot of work.

**Comment by alexaverbuch** [comment]
I'm glad you find it useful!
We're working as fast as we can, but at the moment things are extremely busy and our resources are quite limited.
In saying that, your feedback has been a huge help already, if you have time please continue!
I'll make an issue for documenting this.

**Comment by ArnauPrat** [comment]
Btw @tomersagi 
You can generate a network of any size, this is documented here:
https://github.com/ldbc/ldbc_snb_datagen/wiki/Compilation_Execution
You can specify the target number of Persons, simulation years and start year. But I do not know how the data generator will behave if you ask him to generate a 10 person network :D

**Comment by tomersagi** [comment]
You’re right, my bad.
