### ISSUE TITLE
What if the data generated is really big?

### ISSUE THREAD

**Issue by tomersagi** [ldbc-dev/ldbc_snb_datagen_deprecated2015#20]
Hi,
I want to generate SF 8000 in the near future. It seems strange to me to run the hadoop job, get 8TB of data which are moved to another 8TB of csv files which are then loaded to >8TB of DB storage. That means that to run an 8TB workload I need at least 16 TB and probably more. Are there any plans for an interactive version where the data is loaded to the DB as it is generated? 
Thanks,
Tomer

**Comment by ArnauPrat** [comment]
Hi Tomer, this is definetely something we are going to implement or allow
the users to implement their own serializers, for instance, one that
directly insterts data into the databas.

Regards,

Arnau

**Comment by tomersagi** [comment]
Any timeline on that? I will need it pretty soon...

**Comment by ArnauPrat** [comment]
We dont know. We are currently working to ensure that datagen is able to
generate graphs up to 500+ billion edges. Once this is done, I'll work on
your request, but I expect about one month. If this is very important for
you, you can always download the code and modify it. You should basically
implement the Serializer interface.

Regards,

Arnau

**Comment by tomersagi** [comment]
o.k. please keep updating on this. 
Thanks

**Comment by tomersagi** [comment]
This has been resolved with the introduction of custom serializers.
