### ISSUE TITLE
How do you enable update streams?

### ISSUE THREAD

**Issue by tomersagi** [ldbc-dev/ldbc_snb_datagen_deprecated2015#24]
Hi,
@alexaverbuch  told me and I saw in the code that there is an option "update streams" but I couldn't find it in the configuration instructions. Please update the instructions. 
Thanks

**Comment by ArnauPrat** [comment]
Hi @tomersagi,

It has been documented for a while, in the configuration and execution page. See the table of possible parameters. You just have to set "updateStreams:true" in your params.ini file.
https://github.com/ldbc/ldbc_snb_datagen/wiki/Compilation_Execution
Regards,
Arnau

**Comment by tomersagi** [comment]
oh, sorry, was looking for it in the [configuration](https://github.com/ldbc/ldbc_snb_datagen/wiki/Configuration) page and not on the [compilation](https://github.com/ldbc/ldbc_snb_datagen/wiki/Compilation_Execution) page. 
Thanks
Tomer
