### ISSUE TITLE
supplied default params.ini file does not match documentation

### ISSUE THREAD

**Issue by tomersagi** [ldbc-dev/ldbc_snb_datagen_deprecated2015#7]
Hi,
The default params.ini file supplied here doesn't match the required parameters defined here: https://github.com/ldbc/ldbc_snb_datagen/wiki/Compilation_Execution

This causes an error when running run.sh with the supplied file. 
Specifically, the parameters updateStreams and outputDir are missing. 
Thanks,
Tomer

**Comment by ArnauPrat** [comment]
Hi tomersagi
Thanks for reporting this. I will look into this issue as soon as possible.
Regards
